-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-12-01 20:38:56.416

-- tables
-- Table: Adresy_Czlonkow
CREATE TABLE Adresy_Czlonkow (
    id int  GENERATED by default on null as IDENTITY,
    ulica varchar2(200)  NOT NULL,
    numer_domu varchar2(15)  NOT NULL,
    numer_mieszkania varchar2(15)  NOT NULL,
    kod_pocztowy varchar2(6)  NOT NULL,
    Miasto_id integer  NOT NULL,
    CONSTRAINT Adresy_Czlonkow_pk PRIMARY KEY (id)
) ;

-- Table: Czlonkowie
CREATE TABLE Czlonkowie (
    czlonek_id int  GENERATED by default on null as IDENTITY,
    imie varchar2(40)  NOT NULL,
    nazwisko varchar2(40)  NOT NULL,
    Adresy_Czlonkow_id int  NOT NULL,
    data_przystapienia_do_klubu date  NOT NULL,
    CONSTRAINT Czlonkowie_pk PRIMARY KEY (czlonek_id)
) ;

-- Table: Gmina
CREATE TABLE Gmina (
    id integer  GENERATED by default on null as IDENTITY,
    nazwa varchar2(100)  NOT NULL,
    wojewodztwo_id integer  NOT NULL,
    CONSTRAINT Gmina_pk PRIMARY KEY (id)
) ;

-- Table: Miasto
CREATE TABLE Miasto (
    id integer  GENERATED by default on null as IDENTITY,
    nazwa varchar2(50)  NOT NULL,
    Gmina_id integer  NOT NULL,
    CONSTRAINT Miasto_pk PRIMARY KEY (id)
) ;

-- Table: Naleznosci
CREATE TABLE Naleznosci (
    id integer  GENERATED by default on null as IDENTITY,
    Czlonkowie_czlonek_id int  NOT NULL,
    suma integer  NOT NULL,
    data date  NOT NULL,
    CONSTRAINT Naleznosci_pk PRIMARY KEY (id)
) ;

-- Table: Styl_plywacki
CREATE TABLE Styl_plywacki (
    id int  GENERATED by default on null as IDENTITY,
    nazwa varchar2(100)  NOT NULL,
    CONSTRAINT Styl_plywacki_pk PRIMARY KEY (id)
) ;

-- Table: Wplata
CREATE TABLE Wplata (
    id integer  GENERATED by default on null as IDENTITY,
    kwota integer  NOT NULL,
    data date  NOT NULL,
    metoda_platnosci_id integer  NOT NULL,
    Czlonkowie_czlonek_id int  NOT NULL,
    CONSTRAINT Wplata_pk PRIMARY KEY (id)
) ;

-- Table: grupy
CREATE TABLE grupy (
    id int  GENERATED by default on null as IDENTITY,
    harmonogram_id int  NOT NULL,
    czlonkowie_czlonek_id int  NOT NULL,
    CONSTRAINT grupy_pk PRIMARY KEY (id)
) ;

-- Table: harmonogramy_szkolen
CREATE TABLE harmonogramy_szkolen (
    harmonogram_id int  GENERATED by default on null as IDENTITY,
    trener_id int  NOT NULL,
    Styl_plywacki_id int  NOT NULL,
    dzien_tygodnia varchar2(50)  NOT NULL,
    godzina varchar2(50)  NOT NULL,
    CONSTRAINT harmonogramy_szkolen_pk PRIMARY KEY (harmonogram_id)
) ;

-- Table: metoda_platnosci
CREATE TABLE metoda_platnosci (
    id integer  GENERATED by default on null as IDENTITY,
    metoda_platnosci varchar2(30)  NOT NULL,
    CONSTRAINT metoda_platnosci_pk PRIMARY KEY (id)
) ;

-- Table: najlepszy_wynik
CREATE TABLE najlepszy_wynik (
    id int  GENERATED by default on null as IDENTITY,
    Styl_plywacki_id int  NOT NULL,
    czlonek_id int  NOT NULL,
    data date  NOT NULL,
    najlepszy_wynik varchar2(100)  NOT NULL,
    CONSTRAINT najlepszy_wynik_pk PRIMARY KEY (id)
) ;

-- Table: trenerzy
CREATE TABLE trenerzy (
    trener_id int  GENERATED by default on null as IDENTITY,
    imie varchar2(90)  NOT NULL,
    nazwisko varchar2(90)  NOT NULL,
    CONSTRAINT trenerzy_pk PRIMARY KEY (trener_id)
) ;

-- Table: wojewodztwo
CREATE TABLE wojewodztwo (
    id integer  GENERATED by default on null as IDENTITY,
    nazwa varchar2(50)  NOT NULL,
    CONSTRAINT wojewodztwo_pk PRIMARY KEY (id)
) ;

-- foreign keys
-- Reference: Adresy_Czlonkow_Miasto (table: Adresy_Czlonkow)
ALTER TABLE Adresy_Czlonkow ADD CONSTRAINT Adresy_Czlonkow_Miasto
    FOREIGN KEY (Miasto_id)
    REFERENCES Miasto (id);

-- Reference: Czlonkowie_Adresy_Czlonkow (table: Czlonkowie)
ALTER TABLE Czlonkowie ADD CONSTRAINT Czlonkowie_Adresy_Czlonkow
    FOREIGN KEY (Adresy_Czlonkow_id)
    REFERENCES Adresy_Czlonkow (id);

-- Reference: Gmina_wojewodztwo (table: Gmina)
ALTER TABLE Gmina ADD CONSTRAINT Gmina_wojewodztwo
    FOREIGN KEY (wojewodztwo_id)
    REFERENCES wojewodztwo (id);

-- Reference: Miasto_Gmina (table: Miasto)
ALTER TABLE Miasto ADD CONSTRAINT Miasto_Gmina
    FOREIGN KEY (Gmina_id)
    REFERENCES Gmina (id);

-- Reference: Naleznosci_Czlonkowie (table: Naleznosci)
ALTER TABLE Naleznosci ADD CONSTRAINT Naleznosci_Czlonkowie
    FOREIGN KEY (Czlonkowie_czlonek_id)
    REFERENCES Czlonkowie (czlonek_id);

-- Reference: Table_9_Czlonkowie (table: grupy)
ALTER TABLE grupy ADD CONSTRAINT Table_9_Czlonkowie
    FOREIGN KEY (czlonkowie_czlonek_id)
    REFERENCES Czlonkowie (czlonek_id);

-- Reference: Table_9_harmonogramy_szkolen (table: grupy)
ALTER TABLE grupy ADD CONSTRAINT Table_9_harmonogramy_szkolen
    FOREIGN KEY (harmonogram_id)
    REFERENCES harmonogramy_szkolen (harmonogram_id);

-- Reference: Wplata_Czlonkowie (table: Wplata)
ALTER TABLE Wplata ADD CONSTRAINT Wplata_Czlonkowie
    FOREIGN KEY (Czlonkowie_czlonek_id)
    REFERENCES Czlonkowie (czlonek_id);

-- Reference: Wplata_metoda_platnosci (table: Wplata)
ALTER TABLE Wplata ADD CONSTRAINT Wplata_metoda_platnosci
    FOREIGN KEY (metoda_platnosci_id)
    REFERENCES metoda_platnosci (id);

-- Reference: harmonogramy_plywacki (table: harmonogramy_szkolen)
ALTER TABLE harmonogramy_szkolen ADD CONSTRAINT harmonogramy_plywacki
    FOREIGN KEY (Styl_plywacki_id)
    REFERENCES Styl_plywacki (id);

-- Reference: harmonogramy_szkolen_trenerzy (table: harmonogramy_szkolen)
ALTER TABLE harmonogramy_szkolen ADD CONSTRAINT harmonogramy_szkolen_trenerzy
    FOREIGN KEY (trener_id)
    REFERENCES trenerzy (trener_id);

-- Reference: najlepszy_wynik_Czlonkowie (table: najlepszy_wynik)
ALTER TABLE najlepszy_wynik ADD CONSTRAINT najlepszy_wynik_Czlonkowie
    FOREIGN KEY (czlonek_id)
    REFERENCES Czlonkowie (czlonek_id);

-- Reference: najlepszy_wynik_Styl_plywackli (table: najlepszy_wynik)
ALTER TABLE najlepszy_wynik ADD CONSTRAINT najlepszy_wynik_Styl_plywacki
    FOREIGN KEY (Styl_plywacki_id)
    REFERENCES Styl_plywacki (id);

-- End of file.

